Feature/welcome-vc
santaarturio/TopMovies pull request #25
Opened 2021-04-10 19:56 UTC by santaarturio

## Description

Added new WelcomeVC

### Types of changes

What types of changes does your code introduce to the Connect app?

- [x] New feature (non-breaking change which adds functionality)

2021-04-13 09:53 UTC, RomanTysiachnik requested changes

2021-04-13 09:53 UTC, balavor commented on TopMovies/Connector/Factory/ConnectorFactory.swift
>        curry(
Code feels with some duplications, except that we always have a different type of connector. Can we extract that in some separate function?

2021-04-13 09:53 UTC, balavor commented on TopMovies/Resources/Assembler/Assembler.swift
> +    default: break
If you add more services, you may forget to handle that case over here.
Get used to avoid `defaults` for custom enums or use `@unknown default`

2021-04-13 09:53 UTC, balavor commented on TopMovies/Resources/Passepartout.swift
> +final class Passepartout: KeysConfigurator {
I'd improve naming for that class to identify exactly what does Passepartout handles (`ServicesPassepartout`, etc.)

2021-04-13 23:33 UTC, santaarturio commented on TopMovies/Connector/Factory/ConnectorFactory.swift
>        curry(
> Code feels with some duplications, except that we always have a different type of connector. Can we extract that in some separate function?

50/50, example is added with last commit :]

2021-04-16 16:25 UTC, RomanTysiachnik requested changes

2021-04-16 16:25 UTC, balavor commented on TopMovies/Resources/Generated/AutoPrism.generated.swift~theirs
> +
Reslove `theirs` and `ours` :)

2021-04-21 16:43 UTC, RomanTysiachnik requested changes

2021-04-21 16:43 UTC, RomanTysiachnik commented on TopMovies/Resources/AppDelegate.swift
> +      .map(StreamingService.init(rawValue:))?
`.flatMap` to get rid of `?`

2021-04-21 19:59 UTC, RomanTysiachnik approved these changes

2021-04-21 22:10 UTC, merged